// [ ** AUTOGENERATED ** ]
// Copyright (c) 2001 - 2008 by Content Management AG, Cologne, Germany
// http://www.cm4all.com
// All rights reserved
var _on3_=[
'%3EUETKRV%22ute%3F%291tgu1lu1wvkn1lujgnrgt0lu%29%40%3E1',
'UETKRV%40',
'%3EUETKRV%22ute%3F%291tgu1lu1wvkn1EnkgpvEjgem40lu%29%40%3E1',
'%3EUETKRV%22ute%3F%291crr1igpgtcvgf1k3%3Ap1yue0lu%29%40%3E1',
'yue0okue',
'Hqtou%22ctg%22fgcevkxcvgf%22kp%22rtgxkgy%22oqfg%23',
'lcxcuetkrv%3C%3D',
'KPRWV',
'dwvvqp',
'C',
'v%7Brg',
'hqtoUwdokv',
'yk%7CctfKf',
'',
'Kp%22fgt%22Rtgxkgy%22kuv%22fkg%22Pcxkicvkqp%22fgcmvkxkgtv%23',
'rcigKf',
'fqewogpv',
'ncpiwcig',
'kuYk%7Cctf',
'KF'];
__y(_on3_);
function __y(l0) { 
var re = /\+/gi;
var l7='u'.charCodeAt(0);
var l8='\\'.charCodeAt(0);
for ( var l1=0;(l1<l0.length) ;l1++){
var l3='';
var l4=unescape(l0[l1].replace(re, ' '));
for (var l2=0;l2<l4.length;l2++){
var l5=(l4.charCodeAt(l2))-2;
var l6;
if (l5==l8 && l1 < l0.length+5 && (l4.charCodeAt(l2+1)) - 2 == l7) {
eval('l6 = "\\u' + l4.substring(l2+2,l2+6) + '";');
l2+=5;
} else if (l5==l8 && l1 < l0.length && (l4.charCodeAt(l2+1)) - 2 == l8) {
l6='\\';
l2+=1;
} else if (l5<=0)
l6=String.fromCharCode(l5+255);
else 
l6=String.fromCharCode(l5);
l3+=l6;
}
l0[l1]=l3;
}
}

var _edit=window.top._edit;

var lang;

var country;

I1:{I0:{if (!(window.top.theLanguage)) break I0;
{
lang=window.top.theLanguage;
country=window.top.theCountry;
}

break I1;
}
{
lang=window.top.opener.top.theLanguage;
country=window.top.opener.top.theCountry;
}

}

theLanguage=lang;
theCountry=country;
document.write(_on3_[0]+_on3_[1]);
document.write(_on3_[2]+_on3_[1]);
document.write(_on3_[3]+_on3_[1]);
var __is_internal__=true;

function init(l4857)
{
I2:{if (!(_edit!=null)) break I2;
{
_edit.documentId=l4857;
_edit.previewLoaded();
}

}

deactivateForms();
}

;
function initMozEdit(l4858)
{
_edit.documentId=l4858;
_edit.documentLoaded();
deactivateForms();
}

;
function displayFormHint()
{
alert(I18N.xlate(_on3_[4],_on3_[5]));
}

;
function deactivateForms()
{
var l4859=document.forms;

I3: {
var l4860=0;for (;;l4860++){if (!(l4860<l4859.length)) break I3;{
l4859[l4860].onsubmit=function ()
{
displayFormHint();
return false;

}

;
l4859[l4860].action=_on3_[6];
}

;}}
var l4861=document.getElementsByTagName(_on3_[7]);

I4:{if (!(l4861)) break I4;
{
I5: {
var l4862=0;for (;;l4862++){if (!(l4862<l4861.length)) break I5;{
I6:{if (!(l4861[l4862].type==_on3_[8])) break I6;
{
l4861[l4862].onclick=displayFormHint;
}

}

}

;}}
}

}

var ancs=document.getElementsByTagName(_on3_[9]);

I7:{if (!(ancs)) break I7;
{
I8: {
var l4863=0;for (;;l4863++){if (!(l4863<ancs.length)) break I8;{
I9:{if (!(ancs[l4863].getAttribute(_on3_[10])==_on3_[11])) break I9;
{
ancs[l4863].onclick=displayFormHint;
}

}

}

;}}
}

}

}

;
function changePage(l4864,l4865)
{
I11:{I10:{if (!(_edit!=null)) break I10;
{
_edit.changePage(l4864,l4865);
}

break I11;
}
{
var url=new URL(window.document.location.href);

var l4866=(url.getParameter(_on3_[12],_on3_[13])!=_on3_[13])
;

I13:{I12:{if (!(l4866)) break I12;
{
alert(_on3_[14]);
return ;

url.setParameter(_on3_[15],l4864,true);
}

break I13;
}
{
url.setParameter(_on3_[16],l4864,true);
url.setParameter(_on3_[17],window.top.theLanguage,true);
}

}

url.setParameter(_on3_[18],_on3_[13]+l4866,true);
window.document.location.href=url.toString();
}

}

}

;
function moveToParent()
{
var siteDoc=window.top.getSiteDocument();

var l4867=siteDoc.getElementById(window.top.currentPage);

var parentPage=l4867.parentNode;

I14:{if (!(parentPage!=null)) break I14;
{
var l4868=parentPage.getAttribute(_on3_[19]);

I15:{if (!(l4868)) break I15;
changePage(l4868);
}

}

}

}

;
function n()
{
}

;
